extends: 'eslint:recommended'
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: script
rules:
  indent:
    - error
    - 2
    - MemberExpression: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
